list_1 = ["NEOUSDT", "LTCUSDT", "ADAUSDT", "EOSUSDT", "IOTAUSDT", "XLMUSDT", "ONTUSDT", "ICXUSDT","RLCUSDT"]
list_2 = ["ZILUSDT","ERNUSDT","KLAYUSDT","BONDUSDT","TWTUSDT","GTCUSDT","TORNUSDT"]
list_3 = ["LITUSDT","DODOUSDT","CAKEUSDT","ACMUSDT","OMUSDT","PONDUSDT","DEGOUSDT","IMXUSDT","GLMRUSDT","LOKAUSDT","SCRTUSDT","API3USDT"]
list_4 = ["GRTUSDT","ALPACAUSDT","QUICKUSDT","MBOXUSDT","LINAUSDT","PERPUSDT","XVGUSDT"]
list_5 = ["ORNUSDT","UTKUSDT","XVSUSDT","UNFIUSDT","ROSEUSDT","AVAUSDT","SKLUSDT","DENTUSDT","MFTUSDT","KEYUSDT","DOCKUSDT","C98USDT"]
list_6 = ["ALICEUSDT","LPTUSDT","HBARUSDT","BELUSDT","CKBUSDT","CHRUSDT","BALUSDT","TVKUSDT","MINAUSDT","RAYUSDT" ]
list_7 = ["XRPUSDT","ETCUSDT","VETUSDT","SUPERUSDT","CFXUSDT","EPSUSDT","AUTOUSDT","OPUSDT","LDOUSDT","GALUSDT","NEXOUSDT"]
list_8 = ["LINKUSDT","WAVESUSDT","ONGUSDT","HOTUSDT","FETUSDT","BATUSDT","RSRUSDT","TOMOUSDT"]
list_9 = ["ALGOUSDT","GTOUSDT","DOGEUSDT","DUSKUSDT","ANKRUSDT","WINUSDT","COSUSDT","COCOSUSDT","MTLUSDT"]
list_10 = ["WANUSDT","CHZUSDT","BANDUSDT","BEAMUSDT","XTZUSDT","RENUSDT","RVNUSDT","ENJUSDT","MATICUSDT","ATOMUSDT"]
list_11 = ["TROYUSDT","VITEUSDT","OGNUSDT","TCTUSDT","APEUSDT","ASTRUSDT","GMTUSDT","KDAUSDT"]
list_12 = ["VTHOUSDT","DGBUSDT","MKRUSDT","DCRUSDT","STORJUSDT","MANAUSDT","WOOUSDT","ALPINEUSDT"]
list_13 = ["COTIUSDT","STPTUSDT","DATAUSDT","SOLUSDT","HARDUSDT","DNTUSDT","FLUXUSDT","VOXELUSDT","HIGHUSDT","PEOPLEUSDT","OOKIUSDT","SPELLUSDT"]
list_14 = ["TRBUSDT","SUSHIUSDT","KSMUSDT","EGLDUSDT","RUNEUSDT","FIOUSDT","PYRUSDT","ALCXUSDT","SANTOSUSDT","MCUSDT",]
list_15 = ["ALPHAUSDT","AAVEUSDT","NEARUSDT","FILUSDT","INJUSDT","AKROUSDT","AXSUSDT","MOVRUSDT","CITYUSDT","ENSUSDT","KP3RUSDT"]
list_16 = ["JUVUSDT","PSGUSDT","1INCHUSDT","REEFUSDT","OGUSDT","ATMUSDT","ASRUSDT","CELOUSDT","RIFUSDT"]
list_17 = ["BARUSDT","FORTHUSDT","BAKEUSDT","BURGERUSDT","SLPUSDT","SHIBUSDT","ICPUSDT","ARUSDT","POLSUSDT","MDXUSDT","GALAUSDT","ILVUSDT","YGGUSDT","SYSUSDT"]
list_18 = ["WINGUSDT","UNIUSDT","OXTUSDT","AVAXUSDT","HNTUSDT","FLMUSDT"]
list_19 = ["MDTUSDT","STMXUSDT","KNCUSDT","LRCUSDT","PNTUSDT","COMPUSDT"]
list_20 = ["GNOUSDT","STXUSDT","KAVAUSDT","ARPAUSDT","IOTXUSDT","RLCUSDT","TVKUSDT","MINAUSDT"]
list_21 = ["BLZUSDT","IRISUSDT","KMDUSDT","ANTUSDT","CRVUSDT","SANDUSDT","OCEANUSDT","NMRUSDT","DOTUSDT"]
list_22 = ["LSKUSDT","BNTUSDT","LTOUSDT","MBLUSDT","BETAUSDT","RAREUSDT","LAZIOUSDT","CHESSUSDT","ADXUSDT","AUCTIONUSDT","DARUSDT","BNXUSDT"]
list_23 = ["TKOUSDT","TLMUSDT","IOSTUSDT","CELRUSDT","DASHUSDT","OMGUSDT","MASKUSDT"]
list_24 = ["THETAUSDT","ENJUSDT","MITHUSDT","TFUELUSDT","ONEUSDT","FTMUSDT","TOMOUSDT","PERLUSDT"]
list_25 = ["CLVUSDT","FLOWUSDT"]








